### ISSUE TITLE
Laravel 7.x support?

### ISSUE THREAD

**Issue by JoseCage** [artesaos/migrator#13]
Hello maintainers.

Do you plan to update this package to support[ Laravel 7](https://laravel.com/docs/7.x/upgrade)? or this package has been abandoned? 

As we can see the last update was in 2018.

Thanks.

**Comment by kelcampus** [comment]
Hello @JoseCage 

I installed the package on laravel 7 (adapted for DDD) and the package is working.
It was not necessary to register and publish the MigrationServiceProvider.

**Comment by JoseCage** [comment]
> Hello @JoseCage 
> 
> I installed the package on laravel 7 (adapted for DDD) and the package is working.
> It was not necessary to register and publish the MigrationServiceProvider.
> 
> 

Right. 

In this case I was specifically talking about the updated because L.7 comes with some new improvements/feature that I can't use (with Migrator) If the package don't "updated their methods/dependencies". Something like that

**Comment by JoseCage** [comment]
Is there any plans to keep the package or its abandoned by now?
As we already have Laravel 9 being released this month and the package is becoming outdated 👴🏾 📦.

I will take a look at the source in case I can help in some way. 🚀 

@emtudo /
