### ISSUE TITLE
Rollback não executa na ordem de registro

### ISSUE THREAD

**Issue by tperrelli** [artesaos/migrator#2]
Bom dia galera. Estou com o seguinte cenário.

1. Registro os migrator em uma ordem específica de criação.
2. Crio meu migrator com o total de 21 tabelas.
3. Ao realizar o rollback, o plugin tenta realizar a operação fora da ordem que está na tabela "migration"
Isso ocasiona um erro, pois ele tenta deletar uma tabela que possui dependências.

Todavia, se eu executar o comando "php artisan migrator --step" e realizar o rollback (um a um), funciona normalmente. Eu acredito que não deveria funcionar dessa forma. Se eu estiver esquecendo de algo, podem me dar um auxílio? Valeu!

**Comment by hernandev** [comment]
terei que testar, qual versão do laravel está usando?

**Comment by tperrelli** [comment]
Bom dia man. As iniciais da versão são 5.3. Segunda feira te passo o restante, pois é um projeto do trabalho.

**Comment by hernandev** [comment]
@tperrelli erro confirmado aqui, aparentemente é recente, irei procurar resolver com urgência

**Comment by hernandev** [comment]
@tperrelli ambos `rollback` e `reset` corrigidos. Por favor, atualize para a versão recém lançada **`1.2.0`**

**Comment by tperrelli** [comment]
Muito obrigado!
