### ISSUE TITLE
Call to a member function all() on null

### ISSUE THREAD

**Issue by diegofersan** [artesaos/migrator#5]
Caras, estou rodando laravel 5.1.45.
Quando entro com o comando php artisan migrator, retorna o seguinte erro:

[Symfony\Component\Debug\Exception\FatalThrowableError]  
  Call to a member function all() on null

Tentei reinstalar o package limpando cache. Refiz todo o readme, mas sem sucesso. O erro continua.

**Comment by emtudo** [comment]
Pelo tempo sem resposta, nos desculpe.

Mas imagino que já tenha resolvido o problema, fechando a issue, se tiver problemas, informe que vamos procurar solucionar.
